### ISSUE TITLE
Which version to install ?

### ISSUE THREAD

**Issue by triatomic** [bricco1981/MT7622-mtkwifi#1]
both images uploaded are sysupgrade; which one should i download and install ?

- openwrt-mediatek-mt7622-xiaomi_redmi-router-ax6s-22.03.3-squashfs-sysupgrade.bin

>  OR

- openwrt-mediatek-mt7622-xiaomi_redmi-router-ax6s-squashfs-sysupgrade.bin

**Comment by bricco1981** [comment]
one is 22.03.2 and the other is 22.03.3.
i close this because it's not an issue.
