### ISSUE TITLE
Failed to build openwrt v22.03,lack of luci-lib-jquery-1-4

### ISSUE THREAD

**Issue by hpx502766238** [bricco1981/MT7622-mtkwifi#2]
WARNING: Makefile 'package/package/mtk/luci-app-mtwifi/Makefile' has a dependency on 'luci-lib-jquery-1-4', which does not exist

**Comment by hpx502766238** [comment]
I tried to delete this dependency in Makefile,then build successful.But there are some visual problem in wireless settings view.

**Comment by bricco1981** [comment]
just select  luci-lib-jquery-1-4 and build, i'll close this because is not an issue. you can still ask here.

**Comment by hpx502766238** [comment]
> just select luci-lib-jquery-1-4 and build, i'll close this because is not an issue. you can still ask here.

but I cannot find it in menuconfig....where to download the source code of luci-lib-jquery-1-4?

**Comment by hpx502766238** [comment]
> > just select luci-lib-jquery-1-4 and build, i'll close this because is not an issue. you can still ask here.
> 
> but I cannot find it in menuconfig....where to download the source code of luci-lib-jquery-1-4?
I have found it.It is from the opemwrt18.06 routing feed.
